# This is a monorepo with separate client and server configurations
# Use the wrangler.toml files in the respective subdirectories:
# - client/wrangler.toml for Pages deployment  
# - server/wrangler.toml for Worker deployment